{"navigation":
    [{
        "id":"7276d7f9-b810-4743-8c11-eccb260bbecd",
        "alias":"MW",
        "type":"link",
        "channelExclusions":[],
        "webLargePriority":0,
        "content":{"title":"Men","subTitle":null,"webLargeImageUrl":null,"mobileImageUrl":null},
        "display":null, 
        "style":{"webLargeStyleType":"dark","mobileStyleType":"dark"},
        "link":{
            "linkType":"internal",
            "brandSectionAlias":null,
            "categoryId":null,
            "webUrl":"https://www.asos.com/us/men/",
            "appUrl":null
        },
        "children":[
        {
            "id":"ae28af2b-e3ca-4f2f-a559-9a976a0812d4",
            "alias":null,"type":"container",
            "channelExclusions":[],
            "webLargePriority":0,
            "content":{
                "title":"Home",
                "subTitle":null,
                "webLargeImageUrl":null,
                "mobileImageUrl":null
            },
            "display":{
                "webLargeTemplateId":0,
                "webLargeTemplateName":"",
                "webLargeColumnSpan":1,
                "mobileTemplateId":7,
                "mobileTemplateName":"homepageLinks",
                "mobileDisplayLayout":"list"
            },
            "style":{
                "webLargeStyleType":"dark",
                "mobileStyleType":"noTitle"
            },
            "link":null,
            "children":[{
                "id":"47989db5-0597-43e6-9bee-1348c35590b0",
                "alias":null,
                "type":"link",
                "channelExclusions":["apps","webLarge"],
                "webLargePriority":0,
                "content":{
                    "title":"Home",
                    "subTitle":null,
                    "webLargeImageUrl":"https://images.asos-media.com/navigation/mw_homebuttonnew_1826147",
                    "mobileImageUrl":"https://images.asos-media.com/navigation/mw_homebuttonnew_1826147"
                },
                "display":null,
                "style":{
                    "webLargeStyleType":"dark","mobileStyleType":"dark"
                },
                "link":{
                    "linkType":"internal",
                    "brandSectionAlias":null,
                    "categoryId":null,
                    "webUrl":"https://www.asos.com/us/men/",
                    "appUrl":null
                },
                "children":[]
            }]
        },
        {
            "id":"73db696f-573b-4ff1-8b7f-ccaaea478697",
            "alias":null,
            "type":"container",
            "channelExclusions":["webLarge"],
            "webLargePriority":0,
            "content":{
                "title":"SPEND AND SAVE TEMP",
                "subTitle":null,
                "webLargeImageUrl":null,
                "mobileImageUrl":null
            },
            "display":{
                "webLargeTemplateId":0,
                "webLargeTemplateName":"",
                "webLargeColumnSpan":1,
                "mobileTemplateId":1,
                "mobileTemplateName":"imageBackground",
                "mobileDisplayLayout":"list"
            },
            "style":{
                "webLargeStyleType":"dark",
                "mobileStyleType":"noTitle"
            },
            "link":null,
            "children":[]
        },
        {
            "id":"125a5aba-3f29-4223-8ffc-d1e06d61ec1b",
            "alias":null,
            "type":"container","channelExclusions":["webLarge"],"webLargePriority":0,"content":{"title":"App and Mobile Top Level","subTitle":null,"webLargeImageUrl":null,"mobileImageUrl":null},"display":{"webLargeTemplateId":0,"webLargeTemplateName":"","webLargeColumnSpan":1,"mobileTemplateId":1,"mobileTemplateName":"imageBackground","mobileDisplayLayout":"carousel"},"style":{"webLargeStyleType":"dark","mobileStyleType":"noTitle"},"link":null,"children":[{"id":"cbacb67c-0ef6-4363-a1d3-3b044f7ef330","alias":null,"type":"link","channelExclusions":[],"webLargePriority":0,"content":{"title":"FINAL SALE! EXTRA 25% OFF","subTitle":"Use code: ASOSSALE25PLS","webLargeImageUrl":"https://images.asos-media.com/navigation/mw_awmss2020_orange_2292x762","mobileImageUrl":"https://images.asos-media.com/navigation/mw_awmss2020_orange_2292x762"},"display":null,"style":{"webLargeStyleType":"dark","mobileStyleType":"dark"},"link":{"linkType":"category","brandSectionAlias":null,"categoryId":8409,"webUrl":"https://www.asos.com/us/men/sale/cat/?cid=8409","appUrl":"asos://category?cid=8409"},"children":[]}]},{"id":"bb2385ab-3f26-48cd-80f3-e7414bfb112b","alias":null,"type":"container","channelExclusions":[],"webLargePriority":0,"content":{"title":"Categories","subTitle":null,"webLargeImageUrl":null,"mobileImageUrl":null},"display":{"webLargeTemplateId":0,"webLargeTemplateName":"","webLargeColumnSpan":1,"mobileTemplateId":1,"mobileTemplateName":"imageBackground","mobileDisplayLayout":"list"},"style":{"webLargeStyleType":"noTitle","mobileStyleType":"noTitle"},"link":null,"children":[{"id":"c223e1a9-dc0f-42f5-afca-5cf5988c716b","alias":null,"type":"link","channelExclusions":[],"webLargePriority":12,"content":{"title":"Sale","subTitle":"GET UP TO 70% OFF!","webLargeImageUrl":"https://images.asos-media.com/navigation/mw_awmss2020_blue_2292x762","mobileImageUrl":"https://images.asos-media.com/navigation/mw_awmss2020_blue_2292x762"},"display":null,"style":{"webLargeStyleType":"sale","mobileStyleType":"light"},"link":{"linkType":null,"brandSectionAlias":null,"categoryId":null,"webUrl":null,"appUrl":null},"children":[{"id":"32bc0d58-b649-4871-99b9-67fc4dba4f19","alias":null,"type":"container","channelExclusions":["webLarge"],"webLargePriority":0,"content":{"title":"App & Mobile Promo","subTitle":null,"webLargeImageUrl":null,"mobileImageUrl":null},"display":{"webLargeTemplateId":5,"webLargeTemplateName":"circleImageListLarge","webLargeColumnSpan":1,"mobileTemplateId":1,"mobileTemplateName":"imageBackground","mobileDisplayLayout":"carousel"},"style":{"webLargeStyleType":"noTitle","mobileStyleType":"noTitle"},"link":null,"children":[{"id":"0c165e53-a5fe-48c8-80cd-4800270e6695","alias":null,"type":"link","channelExclusions":[],"webLargePriority":0,"content":{"title":"FINAL SALE! EXTRA 25% OFF","subTitle":"Use code: ASOSSALE25PLS","webLargeImageUrl":"https://images.asos-media.com/navigation/mw_awmss2020_orange_2292x762","mobileImageUrl":"https://images.asos-media.com/navigation/mw_awmss2020_orange_2292x762"},"display":null,"style":{"webLargeStyleType":"dark","mobileStyleType":"dark"},"link":{"linkType":"category","brandSectionAlias":null,"categoryId":8409,"webUrl":"https://www.asos.com/us/men/sale/cat/?cid=8409","appUrl":"asos://category?cid=8409"},"children":[]},{"id":"ca6b68c8-ad50-40f4-a2a7-46ae0479e618","alias":null,"type":"link","channelExclusions":[],"webLargePriority":0,"content":{"title":"Further Reductions","subTitle":null,"webLargeImageUrl":"https://images.asos-media.com/navigation/mw_sale_high_discount_1m_1470749","mobileImageUrl":"https://images.asos-media.com/navigation/mw_sale_high_discount_1m_1470749"},"display":null,"style":{"webLargeStyleType":"dark","mobileStyleType":"dark"},"link":{"linkType":"category","brandSectionAlias":null,"categoryId":28047,"webUrl":"https://www.asos.com/us/men/sale/sale-edit-4/cat/?cid=28047","appUrl":"asos://category?cid=28047"},"children":[]}]},{"id":"7d0c9124-9530-4b9d-9430-ad040ca62f97","alias":null,"type":"container","channelExclusions":[],"webLargePriority":2,"content":{"title":"SHOP BY PRODUCT","subTitle":null,"webLargeImageUrl":null,"mobileImageUrl":null},"display":{"webLargeTemplateId":1,"webLargeTemplateName":"textList","webLargeColumnSpan":2,"mobileTemplateId":3,"mobileTemplateName":"circleImageList","mobileDisplayLayout":"list"},"style":{"webLargeStyleType":"dark","mobileStyleType":"dark"},"link":null,"children":[{"id":"bb5ac850-d970-445e-8876-04ca2e3be65c","alias":null,"type":"link","channelExclusions":[],"webLargePriority":3,"content":{"title":"SALE View all","subTitle":null,"webLargeImageUrl":"https://images.asos-media.com/navigation/mw_sale_viewall_3m_1295799","mobileImageUrl":"https://images.asos-media.com/navigation/mw_sale_viewall_3m_1295799"},"display":null,"style":{"webLargeStyleType":"dark","mobileStyleType":"dark"},"link":{"linkType":"category","brandSectionAlias":null,"categoryId":8409,"webUrl":"https://www.asos.com/us/men/sale/cat/?cid=8409","appUrl":"asos://category?cid=8409"},"children":[]},{"id":"f8e2cf31-bdaf-4d66-9a0c-b51c828b9aeb","alias":null,"type":"link","channelExclusions":["apps","webSmall"],"webLargePriority":2,"content":{"title":"SALE New lines added","subTitle":null,"webLargeImageUrl":"https://images.asos-media.com/navigation/Men-Outlet-New-In-circle-Image-List-42979-106","mobileImageUrl":"https://imag